// src/views/generator/mp/strategy/MapperConfig.vue
<script setup lang="ts">
import { useStrategyConfigStore } from '@/store/mp/strategyconfig'

const strategyconfigStore = useStrategyConfigStore()

const handleReset = () => {
  strategyconfigStore.resetMapper()
}
</script>

<template>
  <el-form
    label-position="top"
    :model="strategyconfigStore.mapper"
  >
    <el-form-item label-width="0">
      <el-button type="warning" @click="handleReset">
        重置
      </el-button>
    </el-form-item>

    <el-row :gutter="24">
      <el-col :sm="12">
        <el-form-item label="覆盖文件">
          <el-radio-group v-model="strategyconfigStore.mapper.fileOverride">
            <el-radio-button :label="true">
              开启
            </el-radio-button>
            <el-radio-button :label="false">
              关闭
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-col>
      <el-col :sm="12">
        <el-form-item label="开启@Mapper注解">
          <el-radio-group v-model="strategyconfigStore.mapper.mapperAnnotation">
            <el-radio-button :label="true">
              开启
            </el-radio-button>
            <el-radio-button :label="false">
              关闭
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-col>

      <el-col :sm="12">
        <el-form-item label="启用BaseResultMap生成">
          <el-radio-group v-model="strategyconfigStore.mapper.baseResultMap">
            <el-radio-button :label="true">
              开启
            </el-radio-button>
            <el-radio-button :label="false">
              关闭
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-col>
      <el-col :sm="12">
        <el-form-item label="启用BaseColumnList">
          <el-radio-group v-model="strategyconfigStore.mapper.baseColumnList">
            <el-radio-button :label="true">
              开启
            </el-radio-button>
            <el-radio-button :label="false">
              关闭
            </el-radio-button>
          </el-radio-group>
        </el-form-item>
      </el-col>

      <el-col :md="24">
        <el-form-item label="父类包名">
          <el-input
            v-model="strategyconfigStore.mapper.superClass"
            placeholder="默认: com.baomidou.mybatisplus.core.mapper.BaseMapper"
          />
        </el-form-item>
      </el-col>
      <el-col :md="12">
        <el-form-item label="格式化mapper文件名称">
          <el-input
            v-model="strategyconfigStore.mapper.formatMapperFilename"
            placeholder="示例: {}Mapper, {}表示占位符"
          />
        </el-form-item>
      </el-col>
      <el-col :md="12">
        <el-form-item label="格式化xml实现类文件名称">
          <el-input
            v-model="strategyconfigStore.mapper.formatXmlFilename"
            placeholder="示例: {}Mapper, {}表示占位符"
          />
        </el-form-item>
      </el-col>
    </el-row>
  </el-form>
</template>

<style lang="css" scoped>
</style>

// src/views/generator/mp/TStrategyConfig/MapperConfig.tsx
import { useStore } from '@/store'
import { defaultMapper } from '@/store/mp/strategyConfig'
import { Mapper } from '@/types/type'
import { renderRadio } from '@/utils/renderRadio'
import {
  Button,
  Form, Grid, Input, Radio,
} from '@arco-design/web-react'
import { FC } from 'react'

const MapperConfig: FC = () => {
  const store = useStore()
  const [form] = Form.useForm<Mapper>()

  reaction(() => store.mp.strategyStore.isHydrated, (isHydrated) => {
    if(isHydrated) {
      form.setFieldsValue({...store.mp.strategyStore.mapper})
    }
  })
  return (
    <Form<Mapper>
      colon
      form={form}
      layout="vertical"
      initialValues={store.mp.strategyStore.mapper}
      onValuesChange={(_, vs) => {
        store.mp.strategyStore.setMapperConfig(vs)
      }}
    >
      <Form.Item>
        <Button status="warning" onClick={() => {form.setFieldsValue(defaultMapper)}}>
          重置
        </Button>
      </Form.Item>

      <Grid.Row gutter={24}>
        <Grid.Col xs={24} md={24}>
          <Form.Item label="覆盖文件" field="fileOverride">
            <Radio.Group type="button">
              {renderRadio()}
            </Radio.Group>
          </Form.Item>
        </Grid.Col>


        <Grid.Col xs={24} md={12}>
          <Form.Item label="设置service接口父类" field="superServiceClass">
            <Input placeholder="示例: com.baomidou.global.BaseService" />
          </Form.Item>
        </Grid.Col>
        <Grid.Col xs={24} md={12}>
          <Form.Item label="设置service实现类父类" field="superServiceImplClass">
            <Input placeholder="示例: com.baomidou.global.BaseServiceImpl" />
          </Form.Item>
        </Grid.Col>

        <Grid.Col xs={24} md={12}>
          <Form.Item label="格式化service接口文件名称" field="formatServiceFilename">
            <Input placeholder="示例: {}Service, {}表示占位符" />
          </Form.Item>
        </Grid.Col>
        <Grid.Col xs={24} md={12}>
          <Form.Item label="格式化service实现类文件名称" field="formatServiceImplFilename">
            <Input placeholder="示例: {}ServiceImpl, {}表示占位符" />
          </Form.Item>
        </Grid.Col>
      </Grid.Row>
    </Form>
  )
}

export default observer(MapperConfig)
