// src/views/generator/strategy/ServiceConfig.vue
<script setup lang="ts">
import { useStrategyConfigStore } from '@/store/modules/mp/strategyconfig'

const strategyconfigStore = useStrategyConfigStore()

const handleReset = () => {
  strategyconfigStore.resetService()
}
</script>

<template>
  <n-form
    label-align="right"
    label-placement="left"
    :label-width="210"
  >
    <n-form-item>
      <n-button type="warning" @click="handleReset">
        重置
      </n-button>
    </n-form-item>

    <n-form-item label="设置service接口父类">
      <n-input
        v-model:value="strategyconfigStore.service.superServiceClass"
        placeholder="示例: com.baomidou.global.BaseService"
      />
    </n-form-item>
    <n-form-item label="设置 service 实现类父类">
      <n-input
        v-model:value="strategyconfigStore.service.superServiceImplClass"
        placeholder="示例: com.baomidou.global.BaseServiceImpl"
      />
    </n-form-item>
    <n-form-item label="格式化service接口文件名称">
      <n-input
        v-model:value="strategyconfigStore.service.formatServiceFilename"
        placeholder="示例: {}Service, {}表示占位符"
      />
    </n-form-item>
    <n-form-item label="格式化service实现类文件名称">
      <n-input
        v-model:value="strategyconfigStore.service.formatServiceImplFilename"
        placeholder="示例: {}ServiceImpl, {}表示占位符"
      />
    </n-form-item>
  </n-form>
</template>

<style lang="css" scoped>
</style>

// src/views/generator/mp/TStrategyConfig/ServiceConfig.tsx
import { useStore } from '@/store'
import { defaultService } from '@/store/mp/strategyConfig'
import { Service } from '@/types/type'
import { renderRadio } from '@/utils/renderRadio'
import {
  Button,
  Form, Grid, Input, Radio,
} from '@arco-design/web-react'
import { FC } from 'react'

const ServiceConfig: FC = () => {
  const store = useStore()
  const [form] = Form.useForm<Service>()

  reaction(() => store.mp.strategyStore.isHydrated, (isHydrated) => {
    if(isHydrated) {
      form.setFieldsValue({...store.mp.strategyStore.service})
    }
  })
  return (
    <Form<Service>
      colon
      form={form}
      layout="vertical"
      initialValues={store.mp.strategyStore.service}
      onValuesChange={(_, vs) => {
        store.mp.strategyStore.setServiceConfig(vs)
      }}
    >
      <Form.Item>
        <Button status="warning" onClick={() => {form.setFieldsValue(defaultService)}}>
          重置
        </Button>
      </Form.Item>

      <Grid.Row gutter={24}>
        <Grid.Col xs={24} md={24}>
          <Form.Item label="覆盖文件" field="fileOverride">
            <Radio.Group type="button">
              {renderRadio()}
            </Radio.Group>
          </Form.Item>
        </Grid.Col>


        <Grid.Col xs={24} md={12}>
          <Form.Item label="设置service接口父类" field="superServiceClass">
            <Input placeholder="示例: com.baomidou.global.BaseService" />
          </Form.Item>
        </Grid.Col>
        <Grid.Col xs={24} md={12}>
          <Form.Item label="设置service实现类父类" field="superServiceImplClass">
            <Input placeholder="示例: com.baomidou.global.BaseServiceImpl" />
          </Form.Item>
        </Grid.Col>

        <Grid.Col xs={24} md={12}>
          <Form.Item label="格式化service接口文件名称" field="formatServiceFilename">
            <Input placeholder="示例: {}Service, {}表示占位符" />
          </Form.Item>
        </Grid.Col>
        <Grid.Col xs={24} md={12}>
          <Form.Item label="格式化service实现类文件名称" field="formatServiceImplFilename">
            <Input placeholder="示例: {}ServiceImpl, {}表示占位符" />
          </Form.Item>
        </Grid.Col>
      </Grid.Row>
    </Form>
  )
}

export default observer(ServiceConfig)
