// src/views/generator/mp/index.tsx
import {
  Button,
  Card,
  Image,
  Message,
  Tabs,
  Typography,
} from '@arco-design/web-react'
import { FC } from 'react'
import mybatisIcon from '@/assets/mybatis.svg'
import DataSourceConfig from './DataSourceConfig'
import TGlobalConfig from './TGlobalConfig'
import TPackageConfig from './TPackageConfig'
import TemplateConfig from './TemplateConfig'
import InjectConfig from './TInjectConfig'
import TStrategyConfig from './TStrategyConfig'
import { useStore } from '@/store'
import { invoke } from '@tauri-apps/api'

const MyBatisPlusGenerator: FC = () => {
  const store = useStore()

  const generateMyBatisPlus = async () => {
    try {
      await invoke('mp_codegen', {config: store.mp.mpConfig})
      Message.success('代码生成成功')
    } catch (error) {
      Message.error(error as string)
    }
  }

  return (
    <Card
      className="h-full p-3"
      cover={<>
        <div className="flex items-center space-x-3 px-4">
          <Image
            src={mybatisIcon}
            width={64}
            preview={false}
          />
          <Typography.Title heading={4}>MyBatisPlus代码生成器</Typography.Title>
        </div>
      </>}
    >
      <DataSourceConfig />

      <Tabs
        type="rounded"
        animation
        lazyload
        destroyOnHide={false}
        size="large"
        defaultActiveTab="GlobalConfig"
      >
        <Tabs.TabPane title="全局配置" key="GlobalConfig">
          <TGlobalConfig />
        </Tabs.TabPane>
        <Tabs.TabPane title="包配置" key="PackageConfig">
          <TPackageConfig />
        </Tabs.TabPane>
        <Tabs.TabPane title="模板配置" key="TemplateConfig">
          <TemplateConfig />
        </Tabs.TabPane>
        <Tabs.TabPane title="注入配置" key="InjectConfig">
          <InjectConfig />
        </Tabs.TabPane>
        <Tabs.TabPane title="策略配置" key="StrategyConfig">
          <TStrategyConfig />
        </Tabs.TabPane>
      </Tabs>

      <Button
        long
        type="primary"
        size="large"
        className="mt5"
        disabled={!store.mp.isInclude}
        onClick={generateMyBatisPlus}
      >
        生成
      </Button>
    </Card>
  )
}

export default observer(MyBatisPlusGenerator)

// src/views/generator/mp/index.vue
<script setup lang="ts">
import { useStrategyConfigStore } from '@/store/mp/strategyconfig'
import DatasourceConfig from './DatasourceConfig.vue'
import GenerateConfig from './GenerateConfig.vue'
import mybatisIcon from '@/assets/mybatis.svg'
import { BasicTableInfo, MpConfig } from '@/types/type'
import { invoke } from '@tauri-apps/api'
import { useDatasourceStore } from '@/store/mp/datasource'
import { useGlobalConfigStore } from '@/store/mp/globalconfig'
import { usePackageConfigStore } from '@/store/mp/packageconfig'
import { useTemplateConfigStore } from '@/store/mp/templateconfig'
import { useInjectConfigStore } from '@/store/mp/injectConfig'
import PageLayout from '@/components/PageLayout/index.vue'

const message = useMessage()
const datasourceConfigStore = useDatasourceStore()
const globalConfigStore = useGlobalConfigStore()
const packageConfigStore = usePackageConfigStore()
const templateConfigStore = useTemplateConfigStore()
const strategyConfigStore = useStrategyConfigStore()
const injectConfigStore = useInjectConfigStore()
const disabled = computed(() => strategyConfigStore.include.length <= 0)

const handleMpGenerate = async () => {
  try {
    const config: MpConfig = {
      datasource: datasourceConfigStore.$state,
      global: globalConfigStore.$state,
      package: packageConfigStore.$state,
      template: templateConfigStore.$state,
      strategy: strategyConfigStore.$state,
      injection: injectConfigStore.$state,
    }
    await invoke('mp_codegen', { config })
    message.success('代码生成成功！')
  } catch (error) {
    message.error(error as string)
  }
}
</script>

<template>
  <PageLayout>
    <template #header>
      <div class="flex items-center space-x-2">
        <el-image
          :src="mybatisIcon"
          style="width: 64px; height: 64px;"
        />
        <span class="text-xl">MyBatisPlus代码生成器</span>
      </div>
    </template>
    <DatasourceConfig />
    <GenerateConfig class="mt-5" />

    <template #footer>
      <el-button
        type="primary"
        class="w-full"
        :disabled="disabled"
        @click="handleMpGenerate"
      >
        生成
      </el-button>
    </template>
  </PageLayout>
</template>

<style lang="css" scoped>
</style>
